### ISSUE TITLE
routing issue

### ISSUE THREAD

**Issue by cj** [jeremyevans/roda#1]
Using the example code below:

``` ruby
require "roda"

class Test < Roda
  route do |r|
    r.is "" do
      "Test"
    end
  end
end

class App < Roda
  route do |r|
    r.is "" do
      'Hello, World!'
    end

    r.on 'test' do
      r.run Test
    end
  end

  plugin :not_found do
    '404'
  end
end
```

visiting `http://localhost` shows `Hello, World!` same with `http://localhost/`.  but when you visit `http://localhost/test` you get a 404, only when you visit `http://localhost/test/` will it work and display `Test`.

p.s. thank you for this great framework.

**Comment by kylekyle** [comment]
In this example, can a route in the sub-app match both "/test/" and "/test"? Or do we just have to copy the logic for both to two routes?

**Comment by jeremyevans** [comment]
There are a few options.  One is to use `r.is [true, ""] do` if you want it only for a specific route.  If you want the behavior modified everywhere, you can use the slash_path_empty plugin, which will treat a patch as fully matched even if it contains just a slash. Alternatively, you can have two routes and have one redirect to the other.
