### ISSUE TITLE
halt plugin: 204 not properly handled

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jeremyevans/roda#101]
I'm using roda with halt plugin. For the delete route case I wanted to reply with 204 status code, so I have:

```ruby
  @resource.destroy
  r.halt 204
```

rack breaks with `Rack::Lint::LintError: Content-Type header found in 204 response, not allowed`. This seems to be due to roda, which by default sets the response default headers and the `Content-Type`. Roda should detect if the status of the response is already set, and if so, only set Content-Type when it's allowed. [List of status codes is here](https://github.com/rack/rack/blob/master/lib/rack/utils.rb#L5799). [This is where roda is setting them](https://github.com/jeremyevans/roda/blob/master/lib/roda.rb#L936).

**Comment by jeremyevans** [comment]
This isn't an issue with the halt plugin, it's just Roda's default behavior.  I've been discussing this with @celsworth, and we are leaning toward checking if the body is empty, and if so, then checking for those statuses and removing Content-Type and Content-Length in such cases.

**Comment by TiagoCardoso1983** [comment]
Thx, that should address the case. I left a comment on the implementation, as I think this could be handled differently (rack has an arguably faster way of addressing it).
