### ISSUE TITLE
Make hooks work with static routes

### ISSUE THREAD

**Issue by mwpastore** [jeremyevans/roda#110]
`before`/`after` hooks (enabled by the hooks plugin) do not work with static routes (enabled by the static_routing plugin). Is there a way to make them work together or are they completely incompatible with each other?

**Comment by jeremyevans** [comment]
They do not currently work together.  static routes are tried before the usual routing tree, while before/after hooks apply to the usual routing tree.  It should be possible to change this in a backwards compatible manner, though.  I'll work on a fix.

**Comment by mwpastore** [comment]
Thank you! I'm happy to take a stab at a PR if you can suggest a strategy. Otherwise, I'll wait for an update!

**Comment by mwpastore** [comment]
Works great! Thanks for the super-speedy turnaround!
