### ISSUE TITLE
Roda::Request#halt returns nil headers

### ISSUE THREAD

**Issue by cptaffe** [jeremyevans/roda#120]
In Puma, `r.halt(404)` returns a nil headers hash. In puma 3.9.1 `/lib/puma/server.rb:679`, puma calls `headers.each`, resulting in a server failure and a 500. I can't tell if this is an error on the part of Puma assuming `headers` will be non-nil or of Roda for returning nil headers.

**Comment by cptaffe** [comment]
`plugin :halt` resolves the issue

**Comment by jeremyevans** [comment]
This is expected.  In the default code, you should only call halt with a rack response (an array with status, headers, and body).  The halt plugin extends this so you can call it with more argument types.  The documentation explains this: http://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/Base/RequestMethods.html#method-i-halt
