### ISSUE TITLE
Alternatives for Block Spaghetti

### ISSUE THREAD

**Issue by r-obert** [jeremyevans/roda#125]
How do you avoid it? 

Looking at an example from the README:
```ruby
r.on "a" do           # /a branch
  check_perm(:A)  
  r.on "b" do         # /a/b branch
    check_perm(:B)  
    r.is "c" do       # /a/b/c request
      r.get do end    # GET  /a/b/c request
      r.post do end   # POST /a/b/c request
    end
    r.get "d" do end  # GET  /a/b/d request
    r.post "e" do end # POST /a/b/e request
  end
end
```
gives me the impression that Roda lends itself to the same pitfalls that Sinatra does, but even more so. The examples also have no implementation. Once you go implement code, you could already be 3 or 4 block-levels deep.

Is there any way, or plans, to map a routing tree to a class that doesn't use blocks as entry point, and less like a DSL? I know this is likely a mailing list question, sorry.

**Comment by r-obert** [comment]
Just noticed "Composition" section in README. 
Sounds perfect for what i have in mind.

**Comment by AMHOL** [comment]
[Shameless self-promotion] https://github.com/AMHOL/roda-flow could be useful to you.

**Comment by r-obert** [comment]
@AMHOL looks cool, i'm looking for something a little more simple, along the lines of:
```ruby
r.get "/name" do
  r.run Class.new {
    def call(env)
      [200, {}, '']
    end
  }
end
```
but without the anonymous class, it'd be regular class. 
i am using webrick servlets until now.
