### ISSUE TITLE
Plugin :assets, a path to an asset file(s)

### ISSUE THREAD

**Issue by GildedHonour** [jeremyevans/roda#128]
1) How can I get a path to a single asset such as a   image from a view? Something like:

`    <img src="<%= asset_path("my_image.png") %>" />`

2) Do I have to enum all images I use accross my application in the "rb" file to be able to access them from views? Something like:

```
 # config.ru
  plugin :assets, 
    images: {img1: "my_image1.png", img2: "my_image2.png"}

   # view.erb
   <img src="<%= asset_path(:img1) %>" />
```

If so, is there a way to avoid that and merely use an image in a view without having to declare it the way I've shown above?

**Comment by jeremyevans** [comment]
The assets plugin currently only handles css and js, not images/fonts/etc.  I would do: `<img src="/images/my_image.png">` unless you have the need for something more fancy.  This assumes you are serving static files and that the file will be returned on a GET request for `/images/my_image.png.` The public plugin is the recommended way to serve static files that if you don't want the images served by the webserver.

Note that as mentioned in the contribution guidelines, GitHub Issues should only be used to file bugs in the library.  General questions like this should be asked on IRC or in the ruby-roda Google Group.
