### ISSUE TITLE
mailer testing

### ISSUE THREAD

**Issue by anazar** [jeremyevans/roda#13]
Any chance of getting mailer testing built into the mailer plugin?

An example would be something like this: https://github.com/cyx/malone#testing

**Comment by jeremyevans** [comment]
It's already built into the underlying `mail` library:

```ruby
Mail.defaults do
  delivery_method :test
end

Mail::TestMailer.deliveries # contains the delivered messages
```

See how the mailer plugin itself is tested: https://github.com/jeremyevans/roda/blob/master/spec/plugin/mailer_spec.rb
