### ISSUE TITLE
public plugin

### ISSUE THREAD

**Issue by bkeane** [jeremyevans/roda#130]
Hello!

It seems the public static file service plugin is not currently functional.

example:
```ruby
# config.ru
require 'roda'
class App < Roda
  plugin :public
  route { |r| r.root { "test" } }
end

run App.freeze.app
```
where ./public/index.html exists

GET /index.html => 404

**Comment by jeremyevans** [comment]
You need to put `r.public` in the appropriate place in your routing tree, depending on what path you want to use to serve static files.  This is mentioned in the documentation for the plugin, though I suppose no explicit example code is shown using it.  In your example:

```ruby
route do |r|
  r.public
  r.root {"test"}
end
```

**Comment by bkeane** [comment]
Mucho gusto! I missed this in the docs apparently. Great project!!
