### ISSUE TITLE
NoMethodError when using content_for

### ISSUE THREAD

**Issue by plujon** [jeremyevans/roda#135]
require 'roda'
    class App < Roda
      plugin :content_for
      plugin :render
      route do |r|
        r.get do
          render(inline: '<% content_for :foo do %><% end %>')
        end
      end
    end
    run App.freeze.app
    # NoMethodError: undefined method `scan' for nil:NilClass
    # 	/var/lib/gems/2.3.0/gems/erubi-1.7.0/lib/erubi.rb:94:in `initialize'
    # 	/var/lib/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/erubi.rb:19:in `new'
    # 	/var/lib/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/erubi.rb:19:in `prepare'
    # 	/var/lib/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:99:in `initialize'
    #       /var/lib/gems/2.3.0/gems/roda-3.4.0/lib/roda/plugins/content_for.rb:65:in `new'
    #       /var/lib/gems/2.3.0/gems/roda-3.4.0/lib/roda/plugins/content_for.rb:65:in `content_for'
    #       <% content_for :foo do %><% end %>:1:in `block in singleton class'

**Comment by jeremyevans** [comment]
Thanks for the report. This does appear to be a bug, I'll work on a fix right away.
