### ISSUE TITLE
Incorrect behaviour for params.has_key?(:key) with indifferent_params plugin

### ISSUE THREAD

**Issue by tpltn** [jeremyevans/roda#136]
Let's say I have a roda router with an indifferent_params plugin.

The error is described by the following code:

```ruby
# GET /users?user_id=1
r.get do
  params[:user_id]
  #=> 1, as expected

  params.has_key?('user_id')
  #=> true, as expected

  params.has_key?(:user_id)
  #=> false, but expected result is true
  # as well as #fetch(:user_id) and possibly some other hash methods
end
```

**Comment by janko-m** [comment]
@tpltn This is expected. Unlike with Rails' `ActiveSupport::HashWithIndifferentAccess`, Roda creates a new Hash with overriden `Hash#default_proc`, which only affects `Hash#[]` but not `Hash#fetch` and others.

**Comment by tpltn** [comment]
@janko-m as for me, it's quite misleading. But ok, it's up to you) Thanks for the quick response!

**Comment by jeremyevans** [comment]
As @janko-m says, this is expected.  Only access (retrieval) is indifferent, not all possible use.
