### ISSUE TITLE
RDoc to Markdown for syntax highlighting

### ISSUE THREAD

**Issue by coisnepe** [jeremyevans/roda#138]
Hi @jeremyevans ,
Would you be interested in a PR converting the RDoc README to the Markdown format, in order to have syntax highlighting for `code` blocks?

**Comment by celsworth** [comment]
I've a feeling it will go the same way as https://github.com/jeremyevans/sequel/pull/1249 (another of jeremy's projects)

**Comment by coisnepe** [comment]
Alright, makes sense. Thanks @celsworth ! I'll just close the issue to spare Jeremy the trouble.

**Comment by jeremyevans** [comment]
Note that the RDoc README supports syntax highlighting, see http://roda.jeremyevans.net/rdoc/files/README_rdoc.html
