### ISSUE TITLE
remove path requirement in mailer plugin

### ISSUE THREAD

**Issue by anazar** [jeremyevans/roda#14]
Can you make it so we can just pass html into the mailer?  We aren't using the render plugin with the mailer.

**Comment by jeremyevans** [comment]
You can already do that.  The mailer plugin does not require the render plugin.  If you look at the mailer plugin specs, you'll see that they test without the render plugin.

Note that in the future, per the contribution guidelines, please ask questions like this on the ruby-roda Google Group or IRC.  GitHub Issues should be used for reporting bugs in Roda, not for questions on how to use Roda.
