### ISSUE TITLE
Should the Gemfile be included in the release?

### ISSUE THREAD

**Issue by assistcontrol** [jeremyevans/roda#141]
Most gems seem to include the Gemfile in the gem tarball. This makes it possible to do ex. `bundle install`. Could roda include the Gemfile in the roda.gemspec too?

**Comment by jeremyevans** [comment]
I'm not in favor of including `Gemfile` in the gem, as it adds to the size and very few people would use it.  If you want to install the development dependencies, you should use the `--development` argument to `gem install` when installing the gem.

**Comment by assistcontrol** [comment]
Understood. FWIW that doesn't work with FreeBSD or other systems that package gems. There the gem tarball is fetched directly, and without the Gemfile development dependencies must be hardcoded in the port's Makefile.

**Comment by jeremyevans** [comment]
If you can parse the dependency information out of the Gemfile, you can parse it out of the gem metadata:

```
tar xf roda-*.gem
gunzip metadata.gz
ruby -ryaml -e 'p YAML.load(File.read("metadata"))'
```

Also, Roda's Gemfile just includes the gemspec, and the gemspec is not included in the gem, so the Gemfile would not work if the gemspec wasn't also included.  If we shipped the Gemfile without the gemspec, you would get:

```
$ bundle install --local

[!] There was an error parsing `Gemfile`: There are no gemspecs at /path/to/roda. Bundler cannot continue.

 #  from /data/code/roda/Gemfile:2
 #  -------------------------------------------
 #  source 'https://rubygems.org'
 >  gemspec
 #  -------------------------------------------
```

**Comment by assistcontrol** [comment]
Ahh got it. Thanks for the explanation!
