### ISSUE TITLE
[json_parser] Overridden `Rack::Request#POST` must ensure it returns a `Hash`

### ISSUE THREAD

**Issue by 13k** [jeremyevans/roda#142]
Returning anything other than a `Hash` in `RequestMethods#POST` will break `Rack::Request#params`.

This happens because `#params` will blindly call `GET.merge(POST)`, without checking `#POST`'s return value. It works within the confines of Rack's own request body parsing strategy: it will only parse multipart/urlencoded forms, which are inherently `Hash`-like, so it makes sense to `merge` it to the URL query parameters.

Rack's strategy falls apart when `#POST` is overridden. Since it can now parse anything and return anything, it is no longer safe to be `merge`d into `GET`.

---

ActionDispatch [applies a workaround](https://github.com/rails/rails/blob/63ec63ca8c1aa8eb222bba51ba4d66a0edf1d585/actionpack/lib/action_dispatch/http/parameters.rb#L13) (for JSON only), by wrapping the parsed value in a `{ _json: data }` structure if `data` (the parsed value) is not a `Hash`.

Rails test case:

```ruby
# routes.rb
post '/', to: 'json#index'

# json_controller.rb
class JsonController < ApplicationController
  def index
    render(plain: format(
      "r.GET: %p\nr.POST: %p\nr.parameters: %p\nparams: %p\n",
      request.GET,
      request.POST,
      request.parameters,
      params.to_unsafe_hash,
    ))
  end
end
```

```
$ curl -g -H 'Content-Type: application/json' -d '[1,2,3]' 'http://localhost:3000/?i=42&arr[]=a&arr[]=b&h[x]=13&h[y]=31'
r.GET: {"i"=>"42", "arr"=>["a", "b"], "h"=>{"x"=>"13", "y"=>"31"}}
r.POST: {"_json"=>[1, 2, 3], "json"=>{"_json"=>[1, 2, 3]}}
r.parameters: {"_json"=>[1, 2, 3], "i"=>"42", "arr"=>["a", "b"], "h"=>{"x"=>"13", "y"=>"31"}, "controller"=>"json", "action"=>"index", "json"=>{"_json"=>[1, 2, 3]}}
params: {"_json"=>[1, 2, 3], "i"=>"42", "arr"=>["a", "b"], "h"=>{"x"=>"13", "y"=>"31"}, "controller"=>"json", "action"=>"index", "json"=>{"_json"=>[1, 2, 3]}}
```

At some point it wraps the value again, probably using the MIME type symbol/key, so it contains 2 top-level entries for the same data. But I'm not sure where it does this, I didn't dig enough into the `autoload` mess that is actionpack.

---

Now, I'm aware that a route expecting a non-`Hash` JSON body and request parameters at the same time would actually be better off by using `r.GET` and `r.POST` separately, but still, if someone inadvertently uses `r.params` to fetch query parameters (as it's so common), an error is raised and the message/backtrace is not entirely helpful, because it will point to a place in the stack that points to Rack's code and it also largely depends on what was passed as the request body:

```
$ curl -s -X POST -H 'Content-Type: application/json' -d '[]' 'http://localhost:9292/err?param1=value1'

TypeError: no implicit conversion of Array into Hash
<...>/gems/rack-2.0.4/lib/rack/request.rb:358:in `merge'
<...>/gems/rack-2.0.4/lib/rack/request.rb:358:in `params'
<...>/gems/rack-2.0.4/lib/rack/request.rb:20:in `params'
<...>/application.rb:38:in `block (4 levels) in <class:Application>'
```

I think it's safer and simple to adopt a strategy like ActionDispatch has.

**Comment by jeremyevans** [comment]
I don't like the idea of doing it by default.  The biggest issue is that it breaks backwards compatibility for callers of r.POST directly.

I would be OK with adding a plugin option for controlling behavior. One option value would be to use a hash with a :_json key for non-hash JSON input.  There may be other behavior that makes sense in some cases, such as ignoring the submitted JSON.  I don't see a point to implementing the double wrapping behavior that ActionDispatch does.
