### ISSUE TITLE
Enable authentication via config in error_email plugin

### ISSUE THREAD

**Issue by fran-worley** [jeremyevans/roda#143]
The `NET::SMTP` start code [here](https://github.com/jeremyevans/roda/blob/master/lib/roda/plugins/error_email.rb) doesn't provide any easy way to supply a custom port, or allow authentication.

I've ended up extending the smtp start code myself to enable it wondered whether you'd consider a PR to add some additional configuration options e.g. 

```
:port # default 25 unless starttls in which case 587
:mail_from_domain # optional
:login # optional
:password # optional
:enable_starttls # default to true if !login.nil? && authtype == :login
:authtype # default to :login if !login.nil?
```

That would mean I could scrap all this 😄:
```
{
  emailer: lambda { |h|
    port = ENV['SMTP_PORT'] || 25
    smtp = Net::SMTP.new(h[:host], Integer(port))
    smtp.enable_starttls_auto
    smtp.start(
      ENV['MAIL_FROM_DOMAIN'],
      ENV['SMTP_USERNAME'],
      ENV['SMTP_PASSWORD'],
      :login
    ) { |s| s.send_message(h[:message], h[:from], h[:to]) }
  }
}
```

In favour of just:
```
{
  mail_from_domain: ENV['MAIL_FROM_DOMAIN'],
  login: ENV['SMTP_USERNAME'],
  password: ENV['SMTP_PASSWORD']
}
```

**Comment by jeremyevans** [comment]
I'm not sure enough users would benefit from the additional options to warrant adding and maintaining support for them, considering that the :emailer option can already be used for any custom configuration or behavior.  Adding support for these options may also lead to the slippery slope of more options being requested, such as forcing the use of STARTTLS and raising an error if it cannot be used, or rescuing mailing errors.

That being said, I'm not completely against the idea.  If you feel strongly that this support should be added, please post on the ruby-roda Google Group and see how other users feel about this.  I'm closing this now, but depending on the feedback received, I may reopen this.

**Comment by fran-worley** [comment]
Thanks For the quick response Jeremy - I've posted this here https://groups.google.com/forum/#!topic/ruby-roda/L8DA591Jik8
