### ISSUE TITLE
can’t set set session’s cookie expire time

### ISSUE THREAD

**Issue by r3jack** [jeremyevans/roda#149]
plugin :sessions, secret:"***"
cookie's expires is: 1969-12-31T23:59:59.000Z

**Comment by jeremyevans** [comment]
You can use the `:cookie_options` plugin option to do so (the key you are looking for is `:expires`, see https://github.com/rack/rack/blob/master/lib/rack/utils.rb#L226).

As specified in the contribution guidlines, please only file an issue on GitHub to report a bug in the library.  If you would like help using Roda, use the Google Group or IRC to ask questions.
