### ISSUE TITLE
Include an option in json parser for requiring the json header

### ISSUE THREAD

**Issue by lancecarlson** [jeremyevans/roda#151]
Do you think it might make sense to add some halt logic if Content-Type: application/json is not provided? Right now it will just silently ignore your parameters if you don't pass in the correct header.

https://github.com/jeremyevans/roda/blob/master/lib/roda/plugins/json_parser.rb

**Comment by jeremyevans** [comment]
I don't think it makes sense to add that to the json_parser plugin.  If the Content-Type isn't application/json, then the json_parser plugin should fallback on rack's normal parameter parsing.  The json_parser plugin is designed to work in applications that accept JSON for some requests and non-JSON for other requests, it only activates if the Content-Type indicates json.

If your application requires that all submitted content must be in JSON format, you could just check for invalid Content-Type settings at the top of the route block and operate accordingly.

One specific setting that is hard coded into the json_parser plugin is `/json/` as a regular expression for the content type.   I'm open to that being specified as an option, please submit a pull request if you would like that.

Note that as specified in the contribution guidelines, requests for new features and general discussion of Roda should happen on the ruby-roda Google Group or IRC.  You should only open an issue on GitHub to report a bug in Roda itself.
