### ISSUE TITLE
typecast_params convert! behaviour broken with recent commit

### ISSUE THREAD

**Issue by celsworth** [jeremyevans/roda#154]
After my recent PR to add `raise: false` support, I've noticed that `typecast_params` seems to be behaving incorrectly since a recent commit.

Given this code:

```ruby
          typecast_params.convert!(symbolize: true) do |tp|
            tp.convert!('destinations') do |d|
              d.array(:any, %w(pools))
            end
            tp.convert!('sources') do |s|
              s.array(:any, %w(discs))
            end
          end
```

And this input to it:

```
{"sources"=>{"discs"=>[64923]}, "destinations"=>{"pools"=>[9999999]}}
```

`master` produces this output (`sources` is not present):

```
{:destinations=>{:pools=>[9999999]}}
```

I started trying other recent versions and was able to determine that the last working commit (so both hashes are in the output) was e5e784572aee567b5f4bea46ce7835b85736a918. It appears to have been broken by ea9e94c1c73f744506ca4277340d6130a4a17bd5?

**Comment by jeremyevans** [comment]
I agree the behavior is a bug and should be fixed.  However, we can't just revert ea9e94c, as that fixed another bug.  I'll try to put together a failing spec, then work on a fix.
