### ISSUE TITLE
Extract send_file into own plugin?

### ISSUE THREAD

**Issue by fran-worley** [jeremyevans/roda#166]
Firstly thanks for all your hard work on this gem - really is a wonderful piece of engineering!

I've recently been working on a project which has required us to enable the entire sinatra_helpers plugin just to get access to the `send_file` helper. 

While not a dealbreaker, I was wondering if you'd considered either releasing some of the methods as standalone plugins or adding some config option to the sinatra_helper plugin to whitelist which helper methods to enable to avoid unnecessary pollution of the response/ request methods?

-  Also apologies - I now remember you prefer requests like this to the google group I totally forgot until after I sent it!

**Comment by jeremyevans** [comment]
I'm fine splitting off send_file into a separate plugin, and have sinatra_helpers just load that plugin.  Please submit a pull request if you would like to implement that.
