### ISSUE TITLE
Request crashes when passed from app with type_routing to app without

### ISSUE THREAD

**Issue by shanecav84** [jeremyevans/roda#170]
I have a Roda app that has installed the `type_routing` plugin via `Roda.plugin`. I'm mounting a separate Roda app without the `type_routing` plugin to handle certain routes.

```ruby
#!/usr/bin/env rackup

require 'bundler/inline'

gemfile(true) do
  source "https://rubygems.org"

  gem 'roda', git: 'https://github.com/jeremyevans/roda', branch: :master
end

require 'roda'

class SeparateApp < Roda
  route do |r|
    r.is { '' }
  end
end

Roda.plugin :type_routing

class App < Roda
  # Installing this way does not cause the error
  # plugin :type_routing

  route do |r|
    r.on('separate-app') { r.run SeparateApp }
  end
end

run App.app
```

[Monkeypatch](https://github.com/jeremyevans/roda/blob/13974467967769c0575c63eaf2483f6aa11b8b75/lib/roda/plugins/type_routing.rb#L177):

```ruby
# lib/roda/plugins/type_routing:177

def _remaining_path(env)
  opts = scope.opts[:type_routing]
  path = super
        
  # The request has passed to a scope without type_routing
  return path if opts.nil?
  ...
```

```
NoMethodError: undefined method `[]' for nil:NilClass
	.../roda-3.22.0/lib/roda/plugins/type_routing.rb:183:in `_remaining_path'
	.../roda-3.22.0/lib/roda.rb:684:in `initialize'
	.../roda-3.22.0/lib/roda.rb:541:in `new'
	.../roda-3.22.0/lib/roda.rb:541:in `initialize'
	.../roda-3.22.0/lib/roda.rb:436:in `new'
	.../roda-3.22.0/lib/roda.rb:436:in `block in base_rack_app_callable'
	.../roda-3.22.0/lib/roda.rb:141:in `call'
	.../roda-3.22.0/lib/roda.rb:973:in `run'
	test.ru:22:in `block (2 levels) in <class:App>'
	.../roda-3.22.0/lib/roda.rb:1174:in `if_match'
	.../roda-3.22.0/lib/roda.rb:819:in `on'
	test.ru:22:in `block in <class:App>'
	.../roda-3.22.0/lib/roda.rb:572:in `_roda_run_main_route'
	.../roda-3.22.0/lib/roda.rb:550:in `block in _roda_handle_main_route'
	.../roda-3.22.0/lib/roda.rb:548:in `catch'
	.../roda-3.22.0/lib/roda.rb:548:in `_roda_handle_main_route'
	.../roda-3.22.0/lib/roda.rb:436:in `block in base_rack_app_callable'
	.../rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
	.../rack-2.0.7/lib/rack/lint.rb:49:in `_call'
	.../rack-2.0.7/lib/rack/lint.rb:37:in `call'
	.../rack-2.0.7/lib/rack/show_exceptions.rb:23:in `call'
	.../rack-2.0.7/lib/rack/common_logger.rb:33:in `call'
	.../rack-2.0.7/lib/rack/chunked.rb:54:in `call'
	.../rack-2.0.7/lib/rack/content_length.rb:15:in `call'
	.../rack-2.0.7/lib/rack/handler/webrick.rb:86:in `service'
	.../ruby/2.6.0/webrick/httpserver.rb:140:in `service'
	.../ruby/2.6.0/webrick/httpserver.rb:96:in `run'
	.../ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
::1 - - [10/Aug/2019:01:01:40 -0400] "GET /separate-app HTTP/1.1" 500 84258 0.0132
```

**Comment by shanecav84** [comment]
There's more to this than just type_routing. The RodaRequest that gets passed to the separate app includes all the plugins of the previous app, which aren't configured in the separate app. After applying the above monkeypatch to type_routing, the common_logger plugin returns:

```
NoMethodError: undefined method `call' for nil:NilClass
  .../roda-3.22.0/lib/roda/plugins/common_logger.rb:57:in `_roda_after_90__common_logger'
```

**Comment by jeremyevans** [comment]
This isn't a code bug. Loading a plugin into a Roda class after subclassing it can break the subclass, because it can override methods in the subclass without setting the data necessary for proper operation in the subclass.  I'm not sure if this is documented, so I'll update the documentation for `plugin` to reflect this.

FWIW, while you can load plugins into Roda itself, that approach is not encouraged.

**Comment by shanecav84** [comment]
That makes sense. I'm working on an app to distribute as a gem that users can mount onto existing Rack apps. Is there a way to do this with Roda, given that a user might load a plugin into the shared Roda class?

**Comment by shanecav84** [comment]
I think that I just won't support shared Roda classes. The docs make it seem like using `Roda.plugin` is a worthwhile approach, but users should create their own subclass to avoid issues like this.

**Comment by jeremyevans** [comment]
The docs mostly use `Roda.plugin` because creating a subclass for every documentation example using plugins can be overly verbose and distracting.  It's definitely preferred to use your own subclass and not modify Roda itself.
