### ISSUE TITLE
Force HTTPS for website

### ISSUE THREAD

**Issue by swrobel** [jeremyevans/roda#183]
I see it's hosted on github pages, so this should help: https://github.blog/2018-05-01-github-pages-custom-domains-https/

The HTTPS url already works, so I think it should be as simple as toggling that setting
https://roda.jeremyevans.net/

**Comment by jeremyevans** [comment]
This was asked for recently on the google group, to which I declined, see https://groups.google.com/forum/#!topic/ruby-roda/1m9KBWn3PAA

**Comment by swrobel** [comment]
This is a weird hill to die on, but it is your hill!
