### ISSUE TITLE
header_matchers plugin can't match content-type

### ISSUE THREAD

**Issue by shanecav84** [jeremyevans/roda#184]
```ruby
class App < Roda
  plugin :header_matchers

  route do |r|
    r.on header: 'content-type' do |content_type|
      # never reached
    end
  end
end

HTTP.headers('content-type' => 'application/some+json').get('http://localhost:9292')
```

Roda is [looking for](https://github.com/jeremyevans/roda/blob/d1fd4ee7765518e431a865341bd62370c1b98659/lib/roda/plugins/header_matchers.rb#L54) `HTTP_CONTENT_TYPE` but it [looks like](https://github.com/rack/rack/blob/ffa6dc789ca2f35f39acab15467321b1f9f1ca75/lib/rack/lint.rb#L298) Rack doesn't prepend `HTTP_` to the `Content-Type` header.

**Comment by jeremyevans** [comment]
Thanks for posting the issue.  This is also true for Content-Length.  I'll fix this issue before the next release.
