### ISSUE TITLE
Precompile assets and production mode

### ISSUE THREAD

**Issue by pusewicz** [jeremyevans/roda#188]
Hi,

I've got my assets configured with

```ruby
  plugin :assets, css: 'app.scss'
```

and in the template I use the `assets(:css)` helper which returns `<link rel="stylesheet"  href="/assets/css/app.scss" />` in development AND production (when `RACK_ENV` is set to production).

Running the precompile task that correctly generates the files does not help and the `assets` helper does not pick up the generated asset files.

My task was taken from the docs.

```ruby
namespace :assets do
  desc "Precompile the assets"
  task :precompile do
    require_relative 'lib/app'
    App.compile_assets
  end
end
```

My Gemfile:

```ruby
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

ruby File.read('.ruby-version').chomp

gem 'roda'
gem 'slim'
gem 'sassc'
gem 'redcarpet'
gem 'puma'
gem 'rake'
```

running on Ruby 2.7.

What am I doing wrong?

Thanks!

**Comment by jeremyevans** [comment]
It looks like you aren't using the `:precompiled` assets plugin option.  You should use that if you want to use precompiled assets.  Can you try that option?

**Comment by pusewicz** [comment]
Yep, that was it! Not sure how I missed that in the docs!

Getting an integrity error now from the computer SHA but I'll figure it out. Thanks so much Jeremy!
