### ISSUE TITLE
perfomance 10x more than puma in my tests

### ISSUE THREAD

**Issue by eduscrakozabrus** [jeremyevans/roda#189]
What do you think about using iodine server instead of puma (https://github.com/boazsegev/iodine)

**Comment by jeremyevans** [comment]
Roda is a rack framework, and works with any rack compatible webserver.  So Roda users can choose whatever rack compatible webserver they want.  I make no recommendations on which webserver to use, though I can say I use Nginx+Unicorn for my production applications and Puma for demo apps I host on Heroku.

As the contribution guidelines state, GitHub Issues should only be used for reporting bugs in Roda.  Please use the ruby-roda Google Group for general questions regarding Roda.
