### ISSUE TITLE
why utf-8 is not a default encoding?

### ISSUE THREAD

**Issue by okliv** [jeremyevans/roda#190]
if i use `render` method in routing, i have non ascii abracadabra texts. why?

i think in general `utf-8` has to be the most universal option. why do i have somehow set it explicitly? how?

**Comment by jeremyevans** [comment]
Roda actually does set a default encoding for templates, to `Encoding.default_external`.  If you are only dealing with UTF-8 data, that's probably something you should set to `'UTF-8'`.  People that don't have a UTF-8 default external encoding shouldn't have a template encoding of UTF-8 forced upon them, in my opinion.

If you are asking how to change the default render encoding: `plugin :render, :template_opts=>{:default_encoding=>Encoding.find('UTF-8')}`.

As this is a question on design choice and not a bug report, per the contribution guidelines, this should be discussed on the Google Group.  GitHub Issues should only be used for bug reports.
