### ISSUE TITLE
jemalloc for roda?

### ISSUE THREAD

**Issue by tomlobato** [jeremyevans/roda#203]
Hy folks,
I`m assessing to migrate from rails to roda and so far it looks great!
Has anyone tried jemalloc for roda? Any hints?

**Comment by havenwood** [comment]
I've used jemalloc with Roda and it works well for keeping memory use low. I can't think of any Roda-specific issues that you'd have with jemalloc. Just install jemalloc and compile Ruby `--with-jemalloc` and it'll _just work_ without changes to your code. Give it a try!

P.S. I think this might be a good type of question for the [Google Group](https://groups.google.com/d/forum/ruby-roda) or [chat.freenode.net/#roda](http://chat.freenode.net/#roda) IRC.

**Comment by tomlobato** [comment]
Great, thanks @havenwood! 
ps: Just subscribed to Roda`s Google Groups.
