### ISSUE TITLE
Roda in production

### ISSUE THREAD

**Issue by Stormcore** [jeremyevans/roda#204]
Hi! I have a couple of questions:
1. Does it utilize a multi-core setup?
2.  If now, how do I run several workers on a machine, like with puma?

**Comment by jeremyevans** [comment]
1. Roda is thread safe and can run multithreaded and/or in multiple processes. To what extent it utilizes multiple cores depends on your webserver (Puma/Unicorn), Ruby implementation (CRuby, JRuby, etc.), and configuration.
2. You should probably ask that question in the appropriate Puma forum.  That's a webserver question, not a Roda question.

As described in the contribution guidelines, GitHub Issues should only be used for filing bug reports about Roda.  If you have questions about Roda, please ask them on the Google Group.  Only use GitHub Issues for filing bug reports.
