### ISSUE TITLE
compile_assets does not work across multiple servers

### ISSUE THREAD

**Issue by cj** [jeremyevans/roda#22]
When using `compile_assets ` on say heroku, the unique id is different for every dyno and the dynos won't always point back to the same dyno which ends up in a 404.  I think to solve this we need an option to set our own unique key.

**Comment by anazar** [comment]
@jeremyevans the css compiled asset is the same everytime but the js one is unique to each dyno.  Strange and problematic since heroku just routes all requests to an available dyno so we mostly get 404 errors.

**Comment by jeremyevans** [comment]
For heroku, you should have a `assets:precompile` rake task that precompiles the assets during slug compilation, as explained in http://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/Assets.html#module-Roda::RodaPlugins::Assets-label-On+Heroku

Are you doing that?

**Comment by cj** [comment]
@jeremyevans sorry, I opened this ticket for anazar.  the rake task used to be there and it was removed which was causing the issue.  they added it back and now it works.  thank you for your help.
