### ISSUE TITLE
How to use common_logger plugin to log information in routes implementation or in specs or other place in the application?

### ISSUE THREAD

**Issue by jiggneshhgohel** [jeremyevans/roda#237]
I have started exploring Roda and as part of that I want to integrate logging feature into my app. I found that I can use CommonLogger plugin. Checking out its [documentation](https://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/CommonLogger.html) and following the instruction I could come up with following:

```
require 'logger'

class Api < Roda
  LOG_FILE_PATH = "./logs/#{ENV['RACK_ENV'] || 'development'}.log"
  plugin :common_logger, Logger.new(LOG_FILE_PATH)

  plugin :json, classes: [Array, Hash], content_type: 'application/json'

  route do |r|
    r.on 'my_path' do
       r.post do
         <my implementation here>
         
         { data: "...." }       
       end
    end
  end
end
```

When I run the specs for this app implemented using rspec and rack-test like following:

**spec/api_spec.rb**

```
RSpec.describe Api do
  let(:app) {
    builder = Rack::Builder.new
    builder.run(described_class)
  }

  context "POST /my_path" do
    it "does expected thing" do
      post '/my_path',  params

      expect(last_response.status).to eq(200)
      ...
      ...
    end
  end
end
```

a `test.log` file gets created under my `project_root/logs` folder with following contents

```
# Logfile created on 2022-01-11 13:01:50 +0530 by logger.rb/v1.4.3
127.0.01 - - [11/Jan/2022:13:01:50 +0530] "POST /my_path " 200 52 0.0002
```

What I am unable to figure out is how I can use the configured logger to log from inside my route implementation or the tests itself? For e.g. do something like

```
  route do |r|
    r.on 'my_path' do
       r.post do
          logger.debug ">>>>>>> debug 1"
         <my implementation here>
          logger.debug ">>>>>>> debug 2"
         ..

         { data: "...." }       
       end
    end
  end
```

```
  context "POST /my_path" do
    it "does expected thing" do
      logger.debug ">>>>>> spec debug 1"
      post '/my_path',  params

      logger.debug ">>>>>> spec debug 2"

      expect(last_response.status).to eq(200)

      logger.debug ">>>>>> spec debug 3"
      ...
      ...
    end
  end
```

In the plugin code here https://github.com/jeremyevans/roda/blob/master/lib/roda/plugins/common_logger.rb#L24 I can see the logger being set against `app.opts[:common_logger]` but how the app opts can be accessed in my app `Api` that I don't know. What I am looking out for is to implement a construct like `Rails.logger` which I can use across the application code be it a route implementation or a utility class or in my specs. Also how can I make the logger log the log_level and also the params received in the request. 

Thanks.

**Comment by jeremyevans** [comment]
`Api.opts[:common_logger]` will work.  You could add a method so you could access it via `Api.logger`.

In terms of setting the log level and also the params, you would have to use a custom logger object.  It's possible, but I wouldn't recommend it. I would recommend copying the common_logger plugin and then modifying it to do what you want instead.

**Comment by jiggneshhgohel** [comment]
@jeremyevans Thanks for the prompt response. By following

>I would recommend copying the common_logger plugin and then modifying it to do what you want instead.

do you mean copying that plugin code as it is in my repo and then doing the necessary modifications and then registering the modified plugin and using the plugin like a roda plugin should be used? Is that what you are suggesting? If yes, then are there any conventions I should follow for doing the same? For e.g in my repo where should I place the the copied plugin code? In a `lib` folder or some other place? I hope you get what I am trying to ask.

BTW that makes me ask one more question:

In my `config.ru` I have following:

```
# Reference: https://github.com/jeremyevans/rack-unreloader#only-reload-in-development-mode-
is_dev_env = ( ENV['RACK_ENV'] == development )

if is_dev_env
 require 'logger'
 logger = Logger.new($stdout)
end

require 'rack/unreloader'

# Reference: https://github.com/jeremyevans/rack-unreloader#handling-subclasses-
Unreloader = Rack::Unreloader.new(subclasses: %w'Roda', logger: logger, reload: is_dev_env) { App }

require_relative 'utils'

# References:
#  https://github.com/jeremyevans/rack-unreloader#requiring-
#  https://github.com/jeremyevans/rack-unreloader#speeding-things-up-
#  https://github.com/jeremyevans/rack-unreloader/issues/13
Unreloader.require('app.rb') { %w(App Api) }

run(is_dev_env ? Unreloader : App.freeze.app ) 
```

As can be seen in dev env a logger is being passed to Unreloader while instantiating it. So is it possible to use the common_logger (whether through the plugin readily available or as per your recommendation the modified one for my needs) to pass to Unreloader as well? This question because I am confused that when `App` (or to be specific `Api`) in my case is not yet loaded then how come I would be able to use `App.opts[:common_logger]` made available by the common-logger plugin. In other words what I am looking out for is directing all logs, whether it be from my application or unreloader, to env-specific log file.

Thanks.

**Comment by jeremyevans** [comment]
> @jeremyevans Thanks for the prompt response. By following
> 
> > I would recommend copying the common_logger plugin and then modifying it to do what you want instead.
> 
> do you mean copying that plugin code as it is in my repo and then doing the necessary modifications and then registering the modified plugin and using the plugin like a roda plugin should be used? Is that what you are suggesting? If yes, then are there any conventions I should follow for doing the same? For e.g in my repo where should I place the the copied plugin code? In a `lib` folder or some other place? I hope you get what I am trying to ask.

Yes, that is what I'm suggesting. There aren't conventions for where to place such a plugin; you can place it whereever it makes sense in your application.  You don't need to register it with Roda, you can pass the plugin module when loading it into your application: `plugin YourLoggerPluginModule, logger_object`.

> As can be seen in dev env a logger is being passed to Unreloader while instantiating it. So is it possible to use the common_logger (whether through the plugin readily available or as per your recommendation the modified one for my needs) to pass to Unreloader as well? This question because I am confused that when `App` (or to be specific `Api`) in my case is not yet loaded then how come I would be able to use `App.opts[:common_logger]` made available by the common-logger plugin. In other words what I am looking out for is directing all logs, whether it be from my application or unreloader, to env-specific log file.

What I would do is create the logger object in config.ru, and pass it when creating the Unreloader as well as when loading your logger plugin in app.rb.  You'll want to avoid an approach where loading app.rb creates the logger, since you need the logger before app.rb is loaded.

**Comment by jiggneshhgohel** [comment]
@jeremyevans Thanks.

Based on your following suggestion

> What I would do is create the logger object in config.ru, and pass it when creating the Unreloader as well as when loading your logger plugin in app.rb.

I could think of following way:


```
class Api < Roda

  class << self
     def set_app_logger=(logger)
       @app_logger = logger
     end
   
     def app_logger
        @app_logger
     end
  end
  

   plugin MyLoggerPluginModule, self.app_logger
    
end
```

and then in `config.ru`

```
is_dev_env = ( ENV['RACK_ENV'] == development )

require 'logger'
logger = Logger.new(env_log_file_path)

require 'rack/unreloader'

Unreloader = Rack::Unreloader.new(subclasses: %w'Roda', logger: (is_dev_env ? logger : nil), reload: is_dev_env) { App }

Unreloader.require('app.rb') { %w(App Api) }

Api.set_app_logger = logger

run(is_dev_env ? Unreloader : App.freeze.app ) 
```

Do you find my approach correct? If not then I would really be thankful to you if you can suggest any other better approach. 

Thanks.

**Comment by jeremyevans** [comment]
Looks like the MyLoggerPluginModule plugin would be passed `nil` as the logger, because the plugin is loaded before `set_app_logger=` is called.

**Comment by jeremyevans** [comment]
Also, this isn't a bug, this is a question about how to use Roda, so I'm closing this now.  We can continue discussion here, but in the future, please use GitHub Discussions to ask questions about Roda.  Only use GitHub Issues for filing bugs.
