### ISSUE TITLE
[feature request] Make the view method (from the render plugin) accept a block like the render method does

### ISSUE THREAD

**Issue by gonubana** [jeremyevans/roda#262]
This would allow

render :layout do
  render :inner, locals: il do
    render :innermost, locals: iml
  end
end

 to become

view :inner, locals: il do
  render :innermost, locals: iml
end

which seems less verbose.

**Comment by jeremyevans** [comment]
This seems like a reasonable change to make, and implementation wise isn't hard to add, so I'll take care of it.  In the future, please submit feature requests as discussions instead of issues.  Issues should only be used for bug reports.
