### ISSUE TITLE
Assets plugin can match any route

### ISSUE THREAD

**Issue by celsworth** [jeremyevans/roda#27]
I noticed a minute ago that my app was returning a JSON structure for an URL that I expected to get a 404 back from. Here's the code:

```ruby
require 'roda'
require 'sass'

class App < Roda
    plugin :assets, {
        css: {
            app: %w(reset.scss),
        },  
    }   
    plugin :json
    
    route do |r|
        r.assets
    end 
    
end

run App
```

I would expect this code to return 404 for anything but `/assets/css/app/reset.scss`? But no:

```
ubuntu:~> GET -Se http://localhost:9292/
GET http://localhost:9292/
200 OK 
Connection: close
Date: Tue, 12 May 2015 22:27:59 GMT
Server: WEBrick/1.3.1 (Ruby/2.2.1/2015-02-26)
Content-Length: 63
Content-Type: application/json
Client-Date: Tue, 12 May 2015 22:27:59 GMT
Client-Peer: 127.0.0.1:9292
Client-Response-Num: 1

[["css","(?-mix:assets\\/css\\/((?-mix:app\\/reset\\.scss)))"]] 
```

It seems the structure returned by `r.assets` is being interpreted by the json plugin and matching any route? The previous advice I've had about `r.assets` is to place it at the end, but this might present problems? It's certainly not what I expected to happen :)

**Comment by jeremyevans** [comment]
Well, this really isn't a bug, it's a consequence of the fact that `r.assets` returns an array for GET requests if it doesn't match, and your route block is returning the value of `r.assets`.  Still, I agree it should be fixed.  I'll commit a fix and make sure it makes tomorrow's 2.3.0 release.
