### ISSUE TITLE
Unfork

### ISSUE THREAD

**Issue by sandstrom** [jeremyevans/roda#281]
This is a great project! 🏅 

To make it more obvious that this is the canonical repository, I'd suggest unforking from the original repo (removing the text "forked from …"). 

To unfork, simply contact Github support and explain that the other repo is stale/old and that you want to unfork. They'll fix it within ~1 day.

Having a non-forked repo will help signal that this is the canonical repo, which helps focusing PRs and issues to this repo.

**Comment by jeremyevans** [comment]
Roda is a fork a Cuba, and I think it's best if that is made obvious.  Cuba isn't stale/old (even if it is not updated as frequently), it's a different project with a different maintainer/goals/etc..  I doubt anyone is confused about Roda's canonical repository, and it doesn't look like any of Roda's PR's or issues has accidentally been filed against Cuba's repository, so I don't think this is a problem in practice.

**Comment by sandstrom** [comment]
Thanks for taking time!

(I disagree, but doesn't matter much)

Roda is great!

**Comment by rubyFeedback** [comment]
> Roda is a fork a Cuba, and I think it's best if that is made obvious.

This may be technically correct, but I am reading "Polished Ruby" right now and roda is mentioned at the least in one
chapter. So I looked it up.

The first example I saw was that it is forked though which I found confusing.

So I think sandstrom has a point. My initial expectation was more like "jeremy wrote this" and "it is perhaps
similar to what he did with sequel". So to me, coming from this point of view, it was confusing to then read
"forked from xyz" on the top left.

I think it would be easier if that would not show up, and you could still mention this in the main README, e
and explain a bit of the history or reasons why it was forked. My initial expection when I see a fork is that the fork is not the "real" project. So now I am confused ... cuba is the real thing and roda is the fork that was abandoned.
(I am aware the last sentence does not apply, but I am referring here to expectations people may have.
I had this expectation just now, for instance, even before reading sandstrom's comment. But I concur
with his conclusion in this regard, IMO.)
