### ISSUE TITLE
env['rack.errors'] parsed as a link in common_logger plugin documentation

### ISSUE THREAD

**Issue by pama** [jeremyevans/roda#284]
https://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/CommonLogger.html

The issue is in this particular line:

> Logs to $stderr instead of [env](https://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/'rack.errors') if explicit logger not passed

It should be:

> Logs to $stderr instead of env['rack.errors'] if explicit logger not passed

I ran rdoc on that particular file, and I **could not** reproduce the issue.

**Comment by pama** [comment]
Actually, I was wrong and I can reproduce the issue. The markup needs to be escaped: `\env['rack.errors']`

**Comment by jeremyevans** [comment]
Thanks for the heads up!  I'll fix this shortly.
