### ISSUE TITLE
Not compatible with Haml >= 6

### ISSUE THREAD

**Issue by mfaughn** [jeremyevans/roda#304]
Haml made breaking changes.

see [here](https://github.com/mfaughn/roda_haml_6_error/tree/main) for demonstration

**Comment by jeremyevans** [comment]
You sure this is a Roda issue and not a Tilt issue?  Roda uses Tilt for template rendering.  Tilt hasn't yet released a version with Haml 6 support, you may have to use the Tilt master branch.

**Comment by mfaughn** [comment]
Yup, you're right.  Problem not coming from Roda.  I replicated the problem in a MWE with a different framework.
