### ISSUE TITLE
Sanitize params when using plugin `error_mail`

### ISSUE THREAD

**Issue by gettalong** [jeremyevans/roda#346]
I'd like to use the `error_mail` plugin and I see that it includes the parameters of the request. This is usually fine but can become problematic if the params contain passwords.

What is the preferred way to sanitize the params? Just doing it myself and deleting the problematic entries from params?

**Comment by jeremyevans** [comment]
I think it would be best to build this into the plugin as an option.  We'd want to handle the environment and session values as well, since they could potentially also need sanitization.  I'll work on that before the next release.

**Comment by gettalong** [comment]
This works great, thank you!
