### ISSUE TITLE
Missing rackup on clean install

### ISSUE THREAD

**Issue by Juksefantomet** [jeremyevans/roda#351]
Hello,

I initialized a new roda project using Gemfile:

```
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'roda'
gem 'roda-http-auth'
gem 'rack-cors'
gem 'pg'
gem 'dotenv'
gem "aws-sdk-s3"

```

normally i would never have to specify rackup as a gem dependency.

Now i had to add `gem 'rackup'`

Is this a deliberate change?

**Comment by janko** [comment]
That's change in Rack 3, the rackup command has been extracted into a separate gem.

**Comment by jeremyevans** [comment]
As mentioned, this is expected in Rack 3, not related to Roda.  If you specify a Rack version < 3 in your Gemfile, then Rack 2 will be installed, and rackup will be available.  You may consider using puma instead of rackup.

**Comment by Juksefantomet** [comment]
Thank you guys for quick replies!

Any specific reason for recommending puma over rackup @jeremyevans

**Comment by jeremyevans** [comment]
Rackup is not a server itself, it just tries to find a server and execute it.  I think puma is rackup's first choice.  Unless you have specific needs, puma is the best choice for a Ruby webserver these days.
