### ISSUE TITLE
Some route issue. (About put, delete and etc.)

### ISSUE THREAD

**Issue by AlexandrButenko** [jeremyevans/roda#48]
Hello, guys!

So, i tried to understand how it works. And now i have a question.

Why we have get and post methods and no put, delete and other?

Maybe there is a way? If i wanna write some restful api with beautiful tree routing - i have to come up with some bad routes...

How can i fix it?

**Comment by janko-m** [comment]
Additional HTTP verbs are provided by the [all_verbs](http://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/AllVerbs.html) plugin, so you just need to do `plugin :all_verbs` in your application.
