### ISSUE TITLE
`content_for` with non-erb templating engines

### ISSUE THREAD

**Issue by plukevdh** [jeremyevans/roda#49]
Playing with HAML in particular and `content_for` doesn't work (generally fails to render or renders inline rather than in specified `content_for :my_tag` location).

I'm unsure why it was implemented with knowledge of `@_out_buf` rather than: a) something more template engine agnostic using some Tilt mechanism or b) a more straightforward bit of code like so: 

```ruby
def content_for(key, &block)
  if block
    @content_for ||= {}
    @content_for[key] = yield
  else
    @content_for && @content_for[key]
  end
end
```

I am willing to work on a PR for this if there is no existing reasoning for the current code that I am unaware of. 

Thanks!

**Comment by jeremyevans** [comment]
It states in the documentation that probably only works with erb templates (http://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/ContentFor.html), so this isn't a bug.  However, I'm definitely open to expanding support to other template engines if there is a simple way to do so.  Please do submit a PR if you get something that works generically, or even just with haml and erb.
