### ISSUE TITLE
NotAllowed plugin documentation

### ISSUE THREAD

**Issue by vais** [jeremyevans/roda#55]
Something in this paragraph does not make sense:
>     # This plugin depends on the all_verbs plugin.  It works by overriding
>     # the verb methods, so it wouldn't work if loaded after the all_verbs
>     # plugin.

`loaded after` or `loaded before`?

https://github.com/jeremyevans/roda/blob/master/lib/roda/plugins/not_allowed.rb#L63-L65

**Comment by janko-m** [comment]
Good catch. To chip in my opinion as well, I don't think this part of documentation is necessary, because it can't happen that `all_verbs` is loaded after `not_allowed` (since `not_allowed` will always load it before).

**Comment by jeremyevans** [comment]
I agree, I'll drop that sentence.  Thanks!
