### ISSUE TITLE
Live / Streaming API?

### ISSUE THREAD

**Issue by activestylus** [jeremyevans/roda#6]
Not an issue as much as an inquiry. I am THIS close to selling my team on Roda, but we do need a bit of async action, mostly in the form of SSE, though there could be room for a full on pub/sub solution down the line.

Curious if you have ever dealt with these specs or how plausible it even is within the scope of a plugin. My own research shows people reaching a dead end in terms of mixing synchronous with asynchronous code, like the ill-fated [Rack Stream](https://github.com/jch/rack-stream) library.

I am personally considering [Rack AMQP](https://github.com/rack-amqp/rack-amqp) to fill this void, but the jury is still out until I can really kick the tires on this badboy.

Thoughts?

**Comment by tobymao** [comment]
This guide helped me, but I couldn't get messages streamed in until i set 

response['Transfer-Encoding'] = 'identity'

**Comment by makevoid** [comment]
thanks @tobymao for pointing this out, I had some code that wasn't working anymore on latest Chrome and adding `response['Transfer-Encoding'] = 'identity'` made it work again! many thanks! 

I think someone should probably update Roda's streaming plugin documentation with your note https://github.com/jeremyevans/roda/blob/master/lib/roda/plugins/streaming.rb#L6 

The alternative I guess is to provide an example implementation of `chunked` (default) encoding where apparently you need to pass the size of the chunk in hex and `/r/n` as separators.
