### ISSUE TITLE
How to implement something like Grape's inline API documentation

### ISSUE THREAD

**Issue by venkatd** [jeremyevans/roda#60]
I'm a big fan of the Grape documentation that goes like:
```ruby
    desc 'OAuth endpoint'
    params do
      requires :provider_name, type: String, values: ['google', 'asana'], desc: 'The provider, such as google or asana'
      requires :state, type: String, desc: 'A securely random string'
      requires :redirect_uri, type: String, desc: 'Final destination to redirect to (on the client)'
      optional :access_token, type: String, desc: 'The access token that you will be using'
    end
    get 'oauth/:provider_name' do
       # ...
    end
```

Any idea how I could accomplish something similar in Roda? Thanks!

**Comment by jeremyevans** [comment]
Roda uses instance-level routing, not class-level routing, so no similar API exists.  One possible approach would be something similar to https://github.com/jeremyevans/roda-route_list, based on parsing comments.

It may be possible to do what you want by building on top of the class_level_routing plugin (http://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/ClassLevelRouting.html) and adding a similar desc/params API, but then you lose some of the advantages of using a routing tree.

Note that questions like this are bested asked on the Google Group (https://groups.google.com/forum/#!forum/ruby-roda), GitHub issues should only be used for bug reports, as explained in the contribution guidelines.
