### ISSUE TITLE
Idiomatic way to implement an authenticate method

### ISSUE THREAD

**Issue by venkatd** [jeremyevans/roda#61]
Suppose I have something like this:

```ruby
class Tasks < Roda
  route do |r|
    r.on 'tasks' do
      authenticate!

      r.get do
        # ...
      end

      r.get ':id' do
        # ...
      end
    end
  end

end
```

The behavior I want is to return a 401 status code with a json error message if authorization header isn't being passed in properly. I *don't* want the following `r.get` statements to get called if the user isn't authenticated.

What's the idiomatic way to deal with this given that have access to the current_user?

Thanks!

**Comment by jeremyevans** [comment]
You would just have `authenticate!` call `request.halt` appropriately if the authentication failed. `request.halt` uses `throw`, immediately returning the response.  There's also the `halt` plugin, which supports additional ways to use `request.halt`.
