### ISSUE TITLE
How to redirect to external page?

### ISSUE THREAD

**Issue by bangn** [jeremyevans/roda#62]
I'm sorry if there is already a solution. I try to find it but no luck.

Currently, in my Roda app, I would like to redirect user to an external page (says `www.foo.bar`).
However, looks like Roda app will redirect to `/www.foo.bar`.

Here is the code:
```
r.root do
    r.redirect "www.foo.bar" # This will be redirect to '/www.foo.bar'
end
```

Is there any way to achieve this?
Thank you

**Comment by rennex** [comment]
Start it with `http://` or `https://`.
