### ISSUE TITLE
Make Roda its own project (rather than a Cuba fork) so that it can be searched

### ISSUE THREAD

**Issue by camjackson** [jeremyevans/roda#63]
This error message is really annoying:

<img width="493" alt="screen shot 2016-03-21 at 3 21 13 pm" src="https://cloud.githubusercontent.com/assets/1930451/13910574/a039a18a-ef78-11e5-8683-64a81bdd1d6a.png">

Would you consider fully detaching roda from cuba?

**Comment by jeremyevans** [comment]
I understand this is annoying, but no.  Roda is a Cuba fork, even if has diverged pretty much completely, and I want to pay due respect to Cuba by making that obvious.

I consider this a bug in GitHub. They should at least make it possible for the creator of the fork to turn on searching, or automatically making forks searchable if the fork has a different name from the parent repository.  Looking at GitHub's documentation, they don't allow searching of repository forks until the fork has more stars than the parent, so another way to fix this would be to get Roda more stars than Cuba.  I certainly don't object to that approach.

**Comment by janko-m** [comment]
I emailed support@github.com about this before:

> Hi Janko,
> 
> Thanks for getting in touch! It's not possible to make a fork appear by default in repository search at the moment 1, your intuition for the reasons why are pretty accurate. So there's no settings on our end that would change this behavior. I can definitely see how valuable it could be for situations like yours however. Though I can't make any promises, we can definitely share this with our search team for consideration.
> 
> In the meantime, the only workaround would be to specifically add the "fork:true" qualifier to your search so forks are returned:
> 
> https://github.com/search?utf8=%E2%9C%93&q=roda+fork%3Atrue&type=Repositories
> 
> Sorry I don't have better news at the moment but I hope that clears things up - thanks,
> Robert
> 
> > There is a Ruby web framework Roda https://github.com/jeremyevans/roda,
> which was forked from another web framework, Cuba
> https://github.com/soveran/cuba. Both are individual frameworks, but one
> happened to be forked from the other because they share some core ideas.
> 
> > The problem is, if I enter "roda" in the GitHub search, this project won't
> come out, because forked repositories are not searchable. Sinatra
> https://github.com/sinatra/sinatra has the same problem. I know that this
> is because it doesn't pay off to make forks searchable, since they are
> usually created only for pull requests, and don't have any individual value
> thus shouldn't clutter the search results.
> 
> > Is there any way we can solve this for these particular projects? Is there
> some way we can detect that a fork has it's own life, and make it appear in
> the search results? First I thought that we can notice that fork has
> different name than the original, which means it was probably intentional,
> but that wouldn't cover Sinatra.

**Comment by camjackson** [comment]
Ok, thanks for the explanation @jeremyevans, I appreciate it.
