### ISSUE TITLE
render plugin fails under slim

### ISSUE THREAD

**Issue by kylekyle** [jeremyevans/roda#64]
The following code works:

```ruby
require 'roda'
require 'slim'

class SlimTest < Roda
  plugin :render, engine: 'slim'

  route do |r|
    r.root do 
      render :index
    end
  end
end

run SlimTest.freeze.app
```

If you change `render` to `view` (with a layout.slim in the right spot), the app stops responding completely. I get "No data received in Chrome". Change it to haml or erb and it works great. Not sure what's happening, but I'm pretty stuck. Ideas?

**Comment by jeremyevans** [comment]
Assuming there is an exception raised, you should be able to get the backtrace for it.  That should show you where the error is.  If I had to guess, Silm is raising an exception in your layout.slim file.

**Comment by kylekyle** [comment]
I might need a little more hand-holding debugging this :) 

I added Rack::CommonLogger and it doesn't even show that Roda is seeing the request. I can't seem to find a backtrace anywhere. The app is completely silent. 

Am I the only one that has tried slim under Roda? I thought the problem might be platform specific, but I tested it on my Mac and Linux box with the same result.

**Comment by jeremyevans** [comment]
This doesn't appear to be a bug in Roda.  Per the contribution guidelines, it's best to ask for help on the IRC channel or the Google Group.  GitHub Issues is not a support forum, it's used solely to handling bug reports.

I tried using slim with roda, and it works fine with the following code:

config.ru:

```ruby
require 'roda'
require 'slim'

class SlimTest < Roda
  plugin :render, engine: 'slim'

  route do |r|
    r.root do
      @author = 'jeremy'
      @year = 2016
      @items = [Struct.new(:name, :price).new('a', 3)]*3
      view :index
    end
  end
end

run SlimTest.freeze.app
```

views/index.slim:

```slim
h2 Index
```

views/layout.slim:

```slim
doctype html
html
  head
    title Slim Examples
    meta name="keywords" content="template language"
    meta name="author" content=@author
    javascript:
      alert('Slim supports embedded javascript!')

  body
    h1 Markup examples

    #content
      p This example shows you how a basic Slim file looks like.

      == yield

      - unless @items.empty?
        table
          - @items.each do |item|
            tr
              td.name = item.name
              td.price = item.price
      - else
        p
         | No items found.  Please add some inventory.
           Thank you!

    div id="footer"
      | Copyright #{@year} #{@author}
```
