### ISSUE TITLE
Plugins SymbolStatus and Halt don't work well together 

### ISSUE THREAD

**Issue by pabloh** [jeremyevans/roda#70]
When using both plugins `:halt` and :symbol_status combined, calling `halt` raises and error when passing the response symbol but works fine with the response code number:

```ruby
class App < Roda
  plugin :halt
  plugin :symbol_status
  
  route do |r|

    post 'thingy' do
      Thingy.create(r.params)
      halt 201 # Works fine
    end

    post 'entity' do
      Entity.create(r.params)
      halt :no_content # Raises an error
    end

  end

end
```

**Comment by jeremyevans** [comment]
This is expected, and changing it would break the existing use of the halt and symbol_views plugins, as mentioned in the halt plugin documentation.
