### ISSUE TITLE
Docs might be not up to date

### ISSUE THREAD

**Issue by antonhalim** [jeremyevans/roda#78]
Hi! I had a little confusion on including my assets into my Roda app. I was following the doc and did `<%= assets(:js) %>` and my browser render literal `<script />` tag into the view. It turns out I need to do double equal sign `==` which will be `<%== assets(:js) %>`instead of single equal sign while the docs here http://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/Assets.html#module-Roda::RodaPlugins::Assets-label-Views didn't mention so or I probably missed it somewhere.

**Comment by jeremyevans** [comment]
You need to use `<%==` if using the render plugin `:escape` option, which isn't the default behavior.  This is documented in the render plugin, but if you think additional documentation would be beneficial, please submit a documentation pull request.
