### ISSUE TITLE
Improve user experience when using Puma

### ISSUE THREAD

**Issue by rosenfeld** [jeremyevans/roda#79]
Hi Jeremy, I'm not sure whether this Puma's behavior is intentional or not. But try running this on Puma:

```ruby
# config.ru
require 'roda'

class App < Roda
  route do |r|
    require_relative 'abc' # it seems like Exceptions inheriting RuntimeError do not cause this, so maybe this is a bug. I'll report to Puma too.
  end
end

run App

# abc.rb
class # any invalid code
```

In Webrick we can see immediately what is the problem but Puma will ignore it silently and would cause ERR_EMPTY_RESPONSE error in Chrome. I guess it would be a good idea for Puma to rescue Exception on `call` and take some action rather than letting it propagate to the web server. What do you think?

**Comment by rosenfeld** [comment]
This will cause the same issue in the browser with Puma, but at least it will report the error to the console:

```ruby
run ->(env) {
  require_relative 'abc'
  [200, {}, []]
}
```

**Comment by rosenfeld** [comment]
I'll report it to Puma anyway because it behaves differently when `raise` is used for example.

**Comment by jeremyevans** [comment]
Since this is server specific, you should probably report it to the server developers.  If you want to rescue exceptions in your Roda application instead of raising them to the server, use the error_handler plugin.

**Comment by rosenfeld** [comment]
https://github.com/puma/puma/issues/1027
