### ISSUE TITLE
Locals aren't rendered in the layout (render plugin)

### ISSUE THREAD

**Issue by jrgns** [jeremyevans/roda#80]
Given the following app:

```ruby
# app.rb
require 'roda'

class App < Roda
  plugin :render

  route do |r|
    r.root do
      @instance = 'Instance Var'
      view 'test', locals: { local: 'Local Var' }
    end
  end
end

```
```html
#views/layout.erb
<html><body>
<h2>Layout</h2>
<p>
Instance: <%= defined?(@instance) ? @instance : 'None'  %><br>
Local: <%= defined?(local) ? local : 'None' %>
</p>

<%= yield %>
</body></html>

```
```html
#views/test.erb
<h2>View</h2>

<p>
Instance: <%= defined?(@instance) ? @instance : 'None'  %><br>
Local: <%= defined?(local) ? local : 'None' %>
</p>
```

The outcome is:

> Layout
> 
> Instance: Instance Var  
> Local: None
> 
> View
> 
> Instance: Instance Var  
> Local: Local Var 

Instead of

> Layout
> 
> Instance: Instance Var  
> Local: Local Var
> 
> View
> 
> Instance: Instance Var  
> Local: Local Var

**Comment by jeremyevans** [comment]
This is the expected and specified behavior.  You need to pass layout options via `:layout_opts` (e.g. `layout_opts:{ locals: { local: 'Local Var' }}`).  This allows you to specify different locals to the layout than to the view itself.

I suppose we could consider an option (off by default) to the render plugin that would automatically merge the view template :locals into the layout template :locals.  I can probably work on that before the next release.

**Comment by jrgns** [comment]
Cool. It is somewhat confusing if you're coming from sinatra or something similiar where the passed variables are available in both the layout and the template.

My specific use case is to have the same value in the `title` tag and somewhere on the page.

I saw the `layout_opts` option, but didn't realize that `locals` can be passed to the layout specifically. Maybe just make it clearer in the docs?

**Comment by jeremyevans** [comment]
I can definitely see where it can cause issues.  It's not a problem if you pass data to the view implicitly via instance variables (like sinatra, view scope is the same as route scope), but some people prefer the more explicit approach by specifying locals.

I'll improve the docs as well, but I do think it would be good to support using :locals for both the view template and layout template via an option.

**Comment by janko-m** [comment]
How about `:locals` being automatically passed to the layout template, and any locals specified in `:layout_opts` would be merged with `:locals`, overriding variables with the same name?

**Comment by jeremyevans** [comment]
That's basically what the option would do.  It can't be the default behavior (at least not till Roda 3), as it would affect backwards compatibility.

With this option, here is how I'm planning to populate locals, in terms of priority (least to greatest):

* Plugin :locals
* Plugin :layout_opts => :locals
* method :locals
* method :layout_opts => :locals

**Comment by jrgns** [comment]
Sounds great.

**Comment by jrgns** [comment]
Thanx!

Further to this, I see that the locals passed to a template / layout aren't inherited by partials either. Is this intentional, or an omission?

The workaround is to obviously pass the locals to the partial call:

```
<%= partial('navbar', locals: { title: title }) %>
```

**Comment by jeremyevans** [comment]
That is intentional.  Note that templates are cached per combination of locals, so just blinding merging locals into partials could lead to increased memory usage (possibly combinatoric memory usage in edge cases with nested partials).

You could probably use the view_options plugin, which allows you to set locals in one place and use them for all template renders.

**Comment by jrgns** [comment]
Cool, thanx, looks useful.
