### ISSUE TITLE
Hyphen in Dynamic URL not working with NGINX

### ISSUE THREAD

**Issue by fearnowrath** [jeremyevans/roda#91]
Hello,
I built an application in Roda and tried deploying it to a VPS with NGINX as the server. 
Now this works on my PC:
lets say url is http://localhost:9292/products-10
```
r.get "products-:id" do |id|
...do stuff...
end
```

but on the online server, it gives an internal server error. any idea why?

thanks.

**Comment by janko-m** [comment]
@fearnowrath You just have to check the logs for your app, because most likely the Ruby code threw an error. Anyway, Rack applications are all deployed in the same way, and Roda is Rack-based, so this is most likely not anything Roda-specific.

**Comment by fearnowrath** [comment]
Hi Janko thanks for your reply. The following url works fine on the online server as well, including on my PC:
```
r.get "products/:id" do |id|
...do stuff...
end
```
just when i use '-' instead of '/', it doesn't work on the server but still works on my PC.
I will see if i can find anything on the logs.

**Comment by jeremyevans** [comment]
This should work fine, and the problems shouldn't be related to Roda.  However, looking at the specs, I don't think we specifically test for this, so I'll add a test for it.

**Comment by fearnowrath** [comment]
thank you Jeremy. I think it could have something to do with NGINX then. I will take a look.
thanks.

**Comment by fearnowrath** [comment]
i just tried the following and it worked on the server(just escaped the hyphen and it seemed to work fine)
```
r.get "products-\:id" do |id|
...do stuff...
end
```

**Comment by jeremyevans** [comment]
@fearnowrath that's definitely not the cause of the fix, since `"products-\:id" == "products-:id" # => true`
