### ISSUE TITLE
not_allowed and head plugin not setting Allow HEAD when GET is supported

### ISSUE THREAD

**Issue by dkubb** [jeremyevans/roda#92]
If the `not_allowed` and `head` plugin are used together, the `Allow` header is not including the `HEAD` method when the `GET` method is supported.

**Comment by jeremyevans** [comment]
I suppose the expectation that they would work together is reasonable, even though the two plugins work quite differently.  This should be possible by having the head plugin define `method_not_allowed`, and call super with a modified argument.  This would require that head is loaded after not_allowed, but we can document that.  I'll implement that before the next release.
