### ISSUE TITLE
Is it possible to redirect an error page in Roda?

### ISSUE THREAD

**Issue by fearnowrath** [jeremyevans/roda#94]
I was wondering if it is possible to redirect a 404 or any other error page in roda to some other page lets say the homepage. I am using both error_handler and status_handler plugins but from the docs it appears they need to be used outside the `route do |r| end`. Because of that, I am not able to redirect it. So is there a way to do that?

thanks

**Comment by jeremyevans** [comment]
You can still redirect:

```ruby
plugin :error_handler do |e|
  request.redirect '/somewhere/else'
end
```

If that does not work, please let me know.

**Comment by fearnowrath** [comment]
wow thanks Jeremy, that worked!!

**Comment by prodoxx** [comment]
Any idea why the `request.redirect` does not work in an [eventmachine](https://github.com/eventmachine/eventmachine) block within the controller?

**Comment by jeremyevans** [comment]
@prodoxx  Eventmachine probably doesn't handle the non-local exit correctly.  If so, that's a issue with the use of Eventmachine, not a problem with Roda.
