### ISSUE TITLE
assets: no support for custom types

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jeremyevans/roda#99]
I've started using the assets plugin, and it seems it doesn't support custom types. I assumed that doing:

```ruby
<%= assets(:js, type: "text/babel") %>
```

would replace the type of the script tag, but it doesn't. I guess it's due do https://github.com/jeremyevans/roda/blob/master/lib/roda/plugins/assets.rb#L668-L674 .

Would this be something worth fixing? Pre-compiling babel is possible in the backend, but I was experimenting with frontend processing.

**Comment by celsworth** [comment]
Yes, it's because the type attribute is hardcoded in. I have a partial fix for this, but the remaining problem is `Rack::Util.escape_html` is interfering with the / in text/javascript, and I don't think we want to remove it. But maybe there's an alternative we can use, or we can do the remapping ourselves? Does / actually have to be replaced in an attribute value?

Partial fix (without the escape_html): https://github.com/celsworth/roda/commit/11a78a2c9656c07df65d6e5689a72a1782349617

**Comment by celsworth** [comment]
http://stackoverflow.com/a/5320217 (which refers to the spec at https://html.spec.whatwg.org/multipage/syntax.html#syntax-attributes) seems to indicate `Rack::Utils.escape_html` is the wrong thing to use.

We should only be escaping quotes and ampersands. I propose moving to our own string replacement, perhaps something like one of the fastest methods in https://gist.github.com/thinkerbot/436253/82c6516d14b1ffdb7fd37af57b62a9590f23897f

**Comment by jeremyevans** [comment]
If you want to use babel with front-end processing, it's probably best to have your babel file in the public folder.  The main point of the assets plugin is to do preprocessing (SCSS -> CSS, CoffeeScript/Opal -> JS), so unless you are preprocessing some other format to babel, I'm not sure why you would want to use that.

I'm OK with adding our own hash based escaping method that handles `[&<>'"]`, and switching internal callers to use it.  I'm not sure if we want to add a separate escaping method for just `["'&]`, the HTML spec states "Attribute values are a mixture of text and character references", indicating normal HTML escaping inside attribute values is permissible.

**Comment by jeremyevans** [comment]
After discussion with @celsworth, we don't want to support custom types at this point.  You should probably use the `assets_paths` method to get the paths for the assets, and build the HTML tags yourself if you want to use custom tags, or just use backend processing for babel.

**Comment by TiagoCardoso1983** [comment]
The benefit of such a feature is not only preprocessing, but also modification and or hashstamp. For that , I think it'd be justifiable

**Comment by TiagoCardoso1983** [comment]
I meant modification, bundling, etc.

**Comment by jeremyevans** [comment]
I'm not saying there are no possible uses for custom types.  To be more clear, we just don't think the benefits are worth the cost of developing such a patch ourselves at this point.  If you can produce a patch that supports it and has tests that run correctly on all supported ruby versions (including ruby 1.8), we'll consider it.

**Comment by TiagoCardoso1983** [comment]
fair enough, I'll see about taking a stab at it.

**Comment by pusewicz** [comment]
@jeremyevans I think it would be beneficial to at least support the `type="module"` so that developer can use `import` in the JS assets.

**Comment by jeremyevans** [comment]
@pusewicz I guess I'm OK with that.  Do you want to send a pull request for it?
